### ISSUE TITLE
Detailed installation instructions

### ISSUE THREAD

**Issue by jlinBE** [yingDaWang-UNSW/FS5-Demo#2]
Hi Ying, I wrote some more detailed installation instructions:

Step 1. Install the latest Nvidia graphics drivers and Cuda Framework.

https://www.nvidia.com/download/index.aspx

https://developer.nvidia.com/cuda-downloads?target_os=Windows
&target_arch=x86_64

Step 2. Install latest python
https://www.python.org/downloads/

Step 3. Install python prereqs
press windows-R, type in cmd to open up the command prompt.

type in this to install the prerequisites:

pip install warp-lang pyglet trimesh meshio Rtree gooey matplotlib

Step 5. 
Go to the FS5-Demo folder and doubleclick run.bat  (or "python runFS5GUIDemo.py" in linux)

Here's the content of run.bat to make it work; put run.bat in the same folder as runFS5GUIDemo.py:

python "%~dp0\runFS5GUIDemo.py"

**Comment by yingDaWang-UNSW** [comment]
batchified using this as a foundation thanks
